# .rubocop.yml
require:
  - rubocop-rails
  - rubocop-capybara

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/RedundantReturn:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
