name: Ruby CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run Rubocop
        run: bundle exec rubocop
      - name: Rspec
        run: bundle exec rspec
