name: Ruby CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Run Rubocop
        run: bundle exec rubocop
      - name: Rspec
        run: |
          sudo apt-get install -y sqlite3 libsqlite3-dev
          bundle exec rspec
